//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelsTransport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelsTransport()
        {
            this.Transports = new HashSet<Transport>();
        }
    
        public int ID { get; set; }
        public int ManufacturerID { get; set; }
        public string Model { get; set; }
        public int CountPassangers { get; set; }
        public int CountDisabledPassangers { get; set; }
        public int TypeTransportID { get; set; }
    
        public virtual ManufacrurersTransport ManufacrurersTransport { get; set; }
        public virtual TypesTransport TypesTransport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transports { get; set; }
    }
}
