//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int ID { get; set; }
        public int ModelTransportID { get; set; }
        public int ProductionYear { get; set; }
        public string VIN { get; set; }
        public string RegistrationMark { get; set; }
        public int CityID { get; set; }
        public int DriverID { get; set; }
        public int RouteID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ModelsTransport ModelsTransport { get; set; }
    }
}
