//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LastEnter { get; set; }
        public int RoleID { get; set; }
        public int CityID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual City City { get; set; }
        public virtual Role Role { get; set; }
    }
}
